RNG_SEED: 101
DEVICE: cuda
GPU_NUM: 0
DATALOADER:
  NUM_WORKERS: 6
  PIN_MEMORY: true
MODEL:
  ACCU_GRAD_STEPS: 4
  DROPOUT_P: 0.3
  MAX_SEQ_LENGTH: 200
  TOP_CAP: 36
  TRANS_DEPTH: 4
  TYPE: axial_SANSformer
OPTIM:
  BASE_LR: 0.00059117
  GRAD_CLIP_T: 10.0
  LR_GAMMA: 0.99
  LR_MULT: 0.1
  LR_POLICY: 1cycle
  LR_WARMUP: 1000
  MAX_EPOCHS: 20
  MOMENTUM: 0.9
  NESTEROV: true
  NOAM_FACTOR: 2.0
  WARMUP_FACTOR: 0.1
  WEIGHT_DECAY: 1.0e-05
OVERFIT_ON_BATCH: false
OVERFIT_ON_BATCH_PCT: 0.1
PATHS:
  OUT_DIR: ./experiments/
  EXPERIMENT_NAME: default_axialSANS
  DATAPATH: "path/to/mimic-iv"
  RESULTS_LOG_FILENAME: ""
  PRETRAINED_TRANSFORMER_FILE: ""
TEST:
  BATCH_SIZE: 32
  FILENAME: mimic_test_rem2.feather
  FILENAME2: mimic_test_rem2.feather
TRAIN:
  BATCH_SIZE: 8
  FILENAME: mimic_train_rem2.feather
  LOAD_BEST_CKPT: true
  VALIDATION_SPLIT: 0.2
USE_AMP: false
VERBOSE: true
