RNG_SEED: 101
DEVICE: cuda
GPU_NUM: 0
DATALOADER:
  NUM_WORKERS: 6
  PIN_MEMORY: true
MODEL:
  ACCU_GRAD_STEPS: 1
  DROPOUT_P: 0.3
  EMBED_SIZE: 256
  MAX_SEQ_LENGTH: 200
  NUM_HEADS: 16
  TOP_CAP: 36
  TRANS_DEPTH: 6
  TYPE: add_SANSformer
OPTIM:
  BASE_LR: 0.00059117
  GRAD_CLIP_T: 10.0
  LR_GAMMA: 0.99
  LR_MULT: 0.1
  LR_POLICY: 1cycle
  LR_WARMUP: 1000
  MAX_EPOCHS: 20
  WARMUP_FACTOR: 0.1
  WEIGHT_DECAY: 1.0e-05
OVERFIT_ON_BATCH: false
OVERFIT_ON_BATCH_PCT: 0.5
PATHS:
  OUT_DIR: ./experiments/
  EXPERIMENT_NAME: default_addSANS
  DATAPATH: "path/to/mimic-iv"
  RESULTS_LOG_FILENAME: ""
  PRETRAINED_TRANSFORMER_FILE: ""
TEST:
  BATCH_SIZE: 32
  FILENAME: mimic_test_rem2.feather
  FILENAME2: mimic_test_rem2.feather
TRAIN:
  BATCH_SIZE: 32
  ES_PATIENCE: 0
  ES_THRESHOLD: 0.0001
  EVAL_PERIOD: 1
  FILENAME: mimic_train_rem2.feather
  IS_BINARY_PRED_NEEDED: true
  IS_DIST_PRED_NEEDED: false
  IS_SUPERVISED: false
  IS_TEST_RUN_NEEDED: true
  LOAD_BEST_CKPT: true
  VALIDATION_SPLIT: 0.2
VERBOSE: true
